Feature/arithmetic_ops_backend | Implementação de Operações Aritméticas
h80r-uft/pi-papers-2021.2 pull request #23
Opened 2021-11-18 06:55 UTC by hernandesmacedo

Closes #5 e #6

2021-11-18 07:21 UTC, h80r requested changes
Fiz algumas observações

2021-11-18 07:21 UTC, h80r commented on lib/algorithm/arithmetic_ops.dart
> +    Uint8List pixelsImgA, Uint8List pixelsImgB, int resultImageLength) {
Vírgula no fim da passagem de parâmetros para melhor formatação

2021-11-18 07:21 UTC, h80r commented on lib/algorithm/arithmetic_ops.dart
> +    Uint8List pixelsImgA, Uint8List pixelsImgB, int resultImageLength) {
Vírgula no fim da passagem de parâmetros para melhor formatação

2021-11-18 07:21 UTC, h80r commented on lib/algorithm/arithmetic_ops.dart
> +    Uint8List pixelsImgA, Uint8List pixelsImgB, int resultImageLength) {
Vírgula no fim da passagem de parâmetros para melhor formatação

2021-11-18 07:21 UTC, h80r commented on lib/algorithm/arithmetic_ops.dart
> +    Uint8List pixelsImgA, Uint8List pixelsImgB, int resultImageLength) {
Vírgula no fim da passagem de parâmetros para melhor formatação

2021-11-18 07:21 UTC, h80r commented on lib/algorithm/arithmetic_ops.dart
> +    resultImagePixels[i] = sum < 256 ? sum : 255;
Utilizar o método [`clamp`](https://api.dart.dev/stable/2.14.4/dart-core/num/clamp.html) para limitar o resultado dos pixeis.

2021-11-18 07:21 UTC, h80r commented on lib/algorithm/arithmetic_ops.dart
> +    resultImagePixels[i] = sub > 0 ? sub : 0;
Utilizar o método [`clamp`](https://api.dart.dev/stable/2.14.4/dart-core/num/clamp.html) para limitar o resultado dos pixeis.

2021-11-18 07:21 UTC, h80r commented on lib/algorithm/arithmetic_ops.dart
> +    resultImagePixels[i] = mult < 256 ? mult : 255;
Utilizar o método [`clamp`](https://api.dart.dev/stable/2.14.4/dart-core/num/clamp.html) para limitar o resultado dos pixeis.

2021-11-18 07:21 UTC, h80r commented on lib/algorithm/arithmetic_ops.dart
> +    resultImagePixels[i] = div > 0 ? div : 0;
Utilizar o método [`clamp`](https://api.dart.dev/stable/2.14.4/dart-core/num/clamp.html) para limitar o resultado dos pixeis.

2021-11-18 07:21 UTC, h80r commented on lib/algorithm/arithmetic_ops.dart
> +  }
Pode ser simplificado passando a operação através dos parâmetros dessa função diretamente, em vez de um número que remete à determinada operação

2021-11-18 07:21 UTC, h80r commented on lib/algorithm/arithmetic_ops.dart
> +  Image imgB = decodeImage(imageB!)!;
Remover a nulidade do resultado e dos dois parâmetros de imagem, pois ambos estão sendo afirmados como não nulos logo abaixo.

2021-11-18 07:21 UTC, h80r commented on lib/pages/arithmethics_page.dart
> +// ignore_for_file: avoid_print, duplicate_ignore
Remover

2021-11-18 07:21 UTC, h80r commented on lib/pages/arithmethics_page.dart
> +                  // ignore: avoid_print
Remover comentários desnecessários

2021-11-18 07:21 UTC, h80r commented on lib/pages/arithmethics_page.dart
> +                  // ignore: avoid_print
Remover comentários desnecessários

2021-11-18 07:21 UTC, h80r commented on lib/pages/arithmethics_page.dart
> +                  // ignore: avoid_print
Remover comentários desnecessários

2021-11-18 07:21 UTC, h80r commented on lib/algorithm/arithmetic_ops.dart
> +  // Image smallerImage = pixelsImgA.length <= pixelsImgB.length ? imgA : imgB;
Remover comentários desnecessários

2021-11-18 07:21 UTC, h80r commented on lib/algorithm/arithmetic_ops.dart
> +    // return Image.fromBytes(smallerImage.width, smallerImage.height, sum(pixelsImgA, pixelsImgB, resultImageLength)).getBytes().buffer.asUint8List();
Remover comentários desnecessários

2021-11-20 18:02 UTC, hernandesmacedo commented
Correções realizadas e operações finalizadas. A branch está pronta para nova correção ;)

2021-11-22 12:25 UTC, h80r approved these changes
Ótimo trabalho, bem documentado e escrito.

2021-11-22 12:25 UTC, merged